variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
cache:
  key: "${CI_JOB_NAME}"
  paths:
  - ".cache/pip"
  - ".venv"
stages:
- quality
- tests
".install-deps-template":
  before_script: &1
  - pip install poetry
  - poetry --version
  - poetry config settings.virtualenvs.in-project true
  - poetry install -vv
".quality-template":
  before_script: *1
  image: python:3.6
  stage: quality
".test-template":
  before_script: *1
  stage: tests
  coverage: "/TOTAL.*\\s(\\d+\\.\\d+\\%)/"
  script: make test
  artifacts: &2
    paths:
    - tests/logs
    when: always
    expire_in: 1 week
check-bandit:
  before_script: *1
  image: python:3.6
  stage: quality
  script: make check-bandit
check-black:
  before_script: *1
  image: python:3.6
  stage: quality
  script: make check-black
check-flake8:
  before_script: *1
  image: python:3.6
  stage: quality
  script: make check-flake8
check-isort:
  before_script: *1
  image: python:3.6
  stage: quality
  script: make check-isort
python3.6:
  before_script: *1
  stage: tests
  coverage: "/TOTAL.*\\s(\\d+\\.\\d+\\%)/"
  script: make test
  artifacts: *2
  image: python:3.6
python3.7:
  before_script: *1
  stage: tests
  coverage: "/TOTAL.*\\s(\\d+\\.\\d+\\%)/"
  script: make test
  artifacts: *2
  image: python:3.7
python3.8:
  before_script: *1
  stage: tests
  coverage: "/TOTAL.*\\s(\\d+\\.\\d+\\%)/"
  script: make test
  artifacts: *2
  image: python:3.8
env:
  global:
  - secure: Ervec+ASnvL9k5UxbJ4z0EMtMN21SDUdtED9AH0SwTAxkjpmUl0yHgjz1ylY3DUJT3upIYO1LtZ/C/9gfEupQV2DhwEInTbBnemzY6sOKTN/5HGsrR+Q7+aLIC6DR9KumkzRKOioITiEN6HTcLsDPg1+xrpUl8jweKwINA/1OkqKa2nb9CevN0RiUgACmGgwvVhJQcQHXYRLbMvCPmXXT1dvfNfbIYLjCP1BC/7QuJ+GlqOQOkhXnA3o7rlsAOXqKEdQhLC50Nr9v/BiCjjVV0t9pYvoAX1tssW+8xct6ZZ5yHhBwW1tjd2VArI6dj/rUOhsrBfRFLsQ5mjTBCTb0+h8jIJc/LF5NusVktdbZ5+c/oDLvgX06CM7mq01uGXZgGLBqcjleBqM+85mmOM2MY9q/q878UdNXZ3LpZ/4Pq1PCCbF74eUygmIup7khvVw1C6qtKtzXB1jfBIOyCDlWtlNHXcwWPbZPvjpdZVQdAmA8G9wzDuxYCJuA3yzxqB4HMayCPr+wXzbGvKg8oqPgBTWwlNEDP5UctJTM4zV0NfHTZQyawFOMJKPbr78D+Qg8xSo++v6PsaNs5ibDnqxmrF3eNfQ2ISUQZwEDYayMuGXBAwrs5VCm6ycqAgkEi7z/vguBO1/2nKNpsDlur+Wfqdf4uev9aJW60PPQeNW8d8=
  - secure: RcLNpqAlPG1LD24ZTQUTh+a+njpC8YijvWEbQdBMoBuFppNWAEZ9N7B0sfbzHS43OABQ5n8IGfchDypHnLdldtIGrto1oiXI15QQn365dGLtOxnZlrjgNkS7Xg/YsZEy1fwO/eXLntSlJ+z7y2AyNs1k/zzoM6MCiA6ETWU+QipGh+UAF/OrbsM4rl5zGFzsaPzb+dO958n5MRjmVy+RK+2GbngpTxpdDgwOFpITxoqeNwF7I86/5l8GGBPDRt5AQXikmra51GLtY/aV5Z7rvjOuwkYt76ryXxo5cV3ew8lsdqsy2O0eGaooq2L1eiQi0g/8jmtu7tK/MnNrsowlB/A1KBAt5nMPd1L5vjXscjQhhUl9uY8Of7927tlxa+OIXqQILp5LO+p4t+7tZZvSbWieGbreLJUEE4NjyXFbYkCWz7OkmVxN3z3HbY3PVSD6nhS+wv6Xyll/UofrpH3i6tqQDLyUQYj94r0O2J8zzPnaL/H9ctu+tGrKa/bqUDqw6MjSPt1h0KxO4Lxxtg/W1LZLLt3bIewwjpVITKwjC9bsbuLA7tZS1HlE/eyQBEzL8nKtcLQBho8TW7CNEfX0Bexizk+X2b67AhzPSjuW+iWDnhEi7HlaW4MhjVQmnIk2KPgWb0rh3DGkh5Whwi+Kolgal9H0XkZWCTZxTQmpOeI=
