language: python
python:
    - 3.6
env:
    global:
        - secure: aWXuuH82YssPGSFnHoz0iWbbd6haT9oyLrNLJLD0fdaKpfNKqCNSRcWRKnxf254xwylR7NXfmqIja46A+Obk1E953WALm6pohDnee4OfUv4u52lrZFpfwAiF5Lze1esauNcLGQUI3fAbAELog1bf3VxgzTUR5JIGXT8ib9AsGonSN1NuRT5F2nR93yivWcQPKd3yj9B9VTTa3mqyVkb72Dk+vvOtkNYW3mDHirVAPTwvP9/Oqr3uS8FqayvtB04aWK4Z4Y0c2yPGNL5ty5mLefP/vzoQmGgaQLYiVJqiFWg7ICsOp5ZHt/gPBNPtg7KcncsYmrimx05tVK77qZ7ElbDsKqaff7Ne4gvsdEaWkRvPOSHruXTy8uB3V5pRl+LTh7a7c0Xqt8yOJnN0Gy9HepwMgSGWbpK2dJRb5kHUXlvTAzbA+ILbXdmzksm9rE+3N+HidsBSvK9mCc1j8fRZBCqI74hreJR7sQ2T/Pq5u0jVn4AdfWIK+3Mfwa5co6ecD8YRQS01lph7IB+3fTLy1AksOgKwEqOJF3vvftEFAOkduLqO2tKkW9Ik5tyQ98PansZMTz1YqgGqlRrWW7v6jD7JXyVXuCo9/fIXd2+V6m5qoEuqpS1XNt/UnulG3cl+yhTw0cDyfUWPal8gDMFmn8VDPbJb2IbgNwrvwIZXpEQ=
        - secure: BCbG2emNG0b+oMFI2924LbrZdzwhHNwI7hibHV6dsSM7HoPKr6pNHLjxBEv1xmc0bvPo+Sh+S03WZb6cyD6mlTr6t0kwPH2Qw4boC1DDI80cGVKi1xl/pnM3AOXbHBgAeUpHKwzJAvvtC/inclv5Trp6ICr5lquJtFva4uBIi5zI1f/Wqh8frNL/E9VFu1YLCjmzTPPB5sU3uWQGHp2/Y/4xxm6Z7L5MxOPWcvg6BxvxNX2PWXKrc88a8NNeyxWqk6Dq8nsge7mKD0JBJr0YOZ42hShP9ZLtpwK73DO9cu9g+zLaAlgwka9tLFQfzWEVwolCH6n8oKhjqEXzAEAjyD/Il6W5tvgIv+wtrtIZm+7kdqfm0Oyef0fYDPt29KVznqQ6H8Tws4LmhuuxogVEhp4M/E6vOmPcyqbpsUZp4h9PUXcxMcxUm/ThW22nD0QcapuX8hijObGOO9IWa7BKj4OFNdm6VblSQpzUCMElwWi5zW1JCR1m6oYCpo35tSSNIZCr6o7dqMmfD8HH7RQuvdC7VCK44f1LsAd3FiuTrxG4/F6YpW5Yr7fzBZht3zmQDenaRQvLyXMFJMBhQZG88YXoOnEIM7ZUKRAW7x/ON+GUjW8fPoDQk//v873DMzKeayX7r0T7+bRufohH1bulmPTMOFgZdKAZyGrIvFzo59g=
          before_install:
              - pip install poetry
          install:
              - poetry install
          script:
              - poetry run flake8 ytscraper test
              - poetry run coverage run --source=ytscraper -m unittest discover -b
          before_deploy:
              - poetry config repositories.mypypi http://mypypi.example.com/simple
              - poetry config http-basic.mypypi $MYPYPI_USER $MYPYPI_PASS
              - poetry build -f sdist
          deploy:
              provider: script
              script: poetry publish -r mypypi
              skip_cleanup: true
              on:
                  tags: true
